title: Dylan
subtitle: Hi, I'm Nguyen Quoc Dat
description: >- # this means to ignore newlines until "baseurl:"
  Hi, I'm Nguyen Quoc Dat.

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog


urls:
    - text: Home
      url: /
    - text: About
      url: /about
    - text: Blogs
      url: /blog
    - text: Game Library
      url: /game-library
    - text: CV
      url : /cv


# Edit Author details (For multi authors check _data/authors.yml)

author_logo: profile.png
author: Nguyen Quoc Dat
author_bio: Hi, my name is Nguyen Quoc Dat. I love coding and investing :D
author_email: "nqdat160602@gmail.com"
author_location: Vietnam
author_website_url: "https://nguyenquocdat.info"
typewrite-text: Hello everyone, this is my personal website.
hero_cover_img: cover.jpg # replace this for changing homepage cover (eg. try cover.jpeg). Image should be in /assets/img

# Experiences
author_work_experiences:
            - company_name: Bug Bounty Program
              company_logo: bug-bounty.svg
              company_url: http://nguyenquocdat.info/
              work_duration: Dec 2021 - Present
              designation: Freelance
              description: As a sophomore, I have been learning about the bug bounty program and have learned a lot from it. It's very interesting!
              visibility: true

# Education
author_education_details:
              - college_logo: ptit.png
                college_name: PTIT - Hoc Vien Cong Nghe Buu Chinh Vien Thong
                college_url: https://portal.ptit.edu.vn/
                study_duration: Oct 2020 - Present
                college_degree: Information Security major
                description: Bachelor of Technology
                college_url: https://portal.ptit.edu.vn/
                visibility: true
              - college_logo: thpt.png
                college_name: THPT Thuong Tin
                college_url: https://www.facebook.com/Thuongtintrongtoi/
                study_duration: Aug 2017 - Jun 2020
                college_degree: High School Diploma
                college_url: https://www.facebook.com/Thuongtintrongtoi/
                visibility: true


# Projects
author_project_details:
              # - project_thumbnail: oldschoolrunescape.png
              #   project_title: OldSchool RuneScape
              #   project_description: Worked on the engine team to support the operation and on-going enhancement of the RuneScape engine and associated systems.
              #   project_url: https://www.jagex.com/en-GB/
              #   blog_url: /blog/my-time-working-on-runecape
              #   date: 17th August, 2021
              #   engine: inhouse.png
              #   language: cpp.png
              #   published: jagex.png
              #   role: Intern Game Engine Developer
              #   team: https://www.jagex.com/en-GB/
              #   dev: Jagex
              #   bp: <ul> 
              #           <li>Worked on developing client server architecture</li>
              #           <li>Learnt about what it's like working on a live MMORPG</li>
              #           <li>Learnt about how engine programming works and what engines are like under the hood</li>
              #           <li>Went on multiple livestreams with large audiences</li>
              #        </ul>
              #   visibility: true 
              # - project_thumbnail: jagex.png
              #   project_title: Unannounced MMORPG
              #   project_description: Worked on the gameplay programming for an Unannounced Triple-A MMORPG in pre-production & implemented some core gameplay mechanics.
              #   project_url: https://www.jagex.com/en-GB/
              #   blog_url: /blog/what-ive-learnt-working-on-jagexs-unannounced-mmorpg/
              #   date: 17th July, 2021
              #   engine: unrealengine.png
              #   language: cpp.png
              #   published: jagex.png
              #   role: Intern Gameplay Programmer
              #   team: https://www.jagex.com/en-GB/
              #   dev: Jagex
              #   bp: <ul> 
              #           <li>Implemented core gameplay mechanics for MMORPGs</li>
              #           <li>Used Unreal Engine & C++ to learn the best industry practices</li>
              #           <li>Wrote code using networking & replication</li>
              #           <li>Worked with different diciplines on the development team</li>
              #        </ul>
              #   visibility: true   
              - project_thumbnail: blocky.png
                project_title: Blocky Road
                project_description: A hyper-casual puzzle game, made in 15 hours.
                project_url: https://amy-elliott.itch.io/blockyroads
                blog_url: /blog/blocky-road/
                date: 31st January, 2022
                engine: unity.png
                language: cs.png
                published: itch.png
                role: Solo Project
                dev: Amy Elliott
                bp: <ul> 
                        <li>Programmed a two-way puzzle system:</li-ph>
                            <ul>
                                <li>Made sure there were different challenges on each side.</li>
                                <li>The puzzles can't be solved without the help from the opposite side.</li>
                            </ul>
                        <li>Inspired by mobile games like Crossy Road and Monument Valley</li>
                     </ul>
                visibility: true
              # - project_thumbnail: subsim.png
              #   project_title: Planesman Trainer
              #   project_description: A submarine simulator game which was made for the Royal Navy's recruitment events
              #   project_url: https://www.royalnavy.mod.uk/careers/roles-and-specialisations/services/submarine-service
              #   blog_url: /blog/sub-sim/
              #   date: 9th April, 2021
              #   engine: unity.png
              #   language: cs.png
              #   published: rn.png
              #   role: Lead Programmer
              #   team: http://gamedev.amy-portfolio.com/blog/authors/submariner#/
              #   dev: Team Submariner
              #   bp: <ul> 
              #           <li>Programmed a majority of the main game systems</li-ph>
              #               <ul>
              #                   <li>Worked on the periscope camera and the implementation</li>
              #                   <li>Helped my teammates learn how to use Unity and C# so no one was left hanging without a task</li>
              #               </ul>
              #           <li>Worked on finding assets and royalty-free materials to use for the environment</li>
              #        </ul>
              #   visibility: true
              - project_thumbnail: tsh.png
                project_title: Team Swap Heroes
                project_description: A teamwork-based puzzle game made for Minijam 48.
                project_url: https://horsehead.itch.io/team-swap-heroes 
                blog_url: https://amy-portfolio.com/team-swap-heroes
                date: 31st January, 2022
                engine: unity.png
                language: cs.png
                published: itch.png
                role: Programmer & Designer
                # team: http://gamedev.amy-portfolio.com/blog/authors/teamhorsehead#/
                dev: Team Horsehead
                bp: <ul> 
                        <li>In charge of the main concepting and level designs:</li>
                            <ul>
                                <li>Worked on design, planning, implementing and testing a vast majority of the levels</li>
                                <li>Made the concept designs for the main character models, enemies and environment.</li>
                            </ul>
                        <li>Programmed the obstacle mechanics for each level and helped out with the player mechanics</li>
                     </ul>
                visibility: true
              # - project_thumbnail: BeatCity.png
              #   project_title: Beat City
              #   project_description: A music based platformer game, developed by myself to experiment with music manipulation.
              #   project_url: https://amy-elliott.itch.io/beat-city
              #   date: 24th February, 2020
              #   engine: unity.png
              #   language: cs.png
              #   visibility: false
              # - project_thumbnail: capsays.png
              #   project_title: Captain Says
              #   project_description: An educational action game, published to the Google Playstore.
              #   project_url: https://play.google.com/store/apps/details?id=com.AmyE.CaptainSays&hl=en_GB&gl=US
              #   blog_url: https://amy-portfolio.com/captain-says
              #   date: 31st August, 2019
              #   engine: unity.png
              #   language: cs.png
              #   published: gplaystore.png
              #   role: Programmer & Designer
              #   team: http://gamedev.amy-portfolio.com/blog/authors/teamhorsehead#/
              #   dev: Team Horsehead
              #   bp: <ul>                        
              #           <li>Learnt how to publish games on the Google Playstore.</li>
              #           <li>Programmed and designed the player movement for both webGL & mobile versions</li>
              #           <li>Programmed the enemy system</li>
              #           <li>Programmed the scoring and highscore system</li>
              #           <li>Designed and implemented the UI</li>                        
              #               <ul>
              #                   <li>Researched and implemented music feedback in the background and UI</li>
              #               </ul>
              #        </ul>
              #   visibility: false
              - project_thumbnail: pop.png
                project_title: Poppin Hoppin Unlockin
                project_description: A fantasy-platformer game, developed for a University Gamejam by a group which I lead.
                project_url: https://amy-elliott.itch.io/poppin-hoppin-unlockin
                date: 31st January, 2022
                engine: unity.png
                language: cs.png
                visibility: true

# Professional Games
# author_professional_games:   

# Personal Games
author_personal_games:
              - game_thumbnail: /gamelib/toytactics.png
                game_title: Toy Tactics
                game_release: 4th October, 2021             
                game_blog: /blog/toy-tactics/
                tag1: Tactics
                tag2: Puzzles
                tag3: Artifical Intelligence
                browser_playable: true
                visibility: true 
              - game_thumbnail: /gamelib/tsh.png
                game_title: Team Swap Heroes
                game_release: 24th Febuary, 2020             
                game_blog: /blog/team-swap-heroes/
                tag1: Teamwork
                tag2: Puzzles
                tag3: Time Race
                browser_playable: true
                visibility: true  
              - game_thumbnail: /gamelib/airportgame.png
                game_title: Airport - Lost & Found
                game_release: 31st January, 2021             
                game_blog: /blog/airport-lost-and-found/
                tag1: Crazy Taxi
                tag2: Ragdoll
                tag3: Time Race
                browser_playable: true
                visibility: true 
              - game_thumbnail: /gamelib/intoodeep.png
                game_title: In Too Deep
                game_release: 27th April, 2021             
                game_blog: /blog/in-too-deep/
                tag1: Mining
                tag2: Tycoon
                tag3: Survival
                browser_playable: true
                visibility: true 
              - game_thumbnail: /gamelib/blocky.png
                game_title: Blocky Road
                game_release: 28th October, 2020            
                game_blog: /blog/blocky-road/
                tag1: Hyper Casual
                tag2: Teamwork
                tag3: Puzzles
                browser_playable: true
                visibility: true
              - game_thumbnail: /gamelib/pop.png
                game_title: Poppin Hoppin Unlockin
                game_release: 12th November, 2020            
                game_blog: /blog/poppin-hoppin-unlockin/
                tag1: Platformer
                tag2: Fantasy
                tag3: Puzzles
                browser_playable: true
                visibility: true 
              - game_thumbnail: /gamelib/beatcity.png
                game_title: Beat City
                game_release: 20th Feburary, 2020            
                game_blog: /blog/beat-city/
                tag1: Music & Rhythm
                tag2: Cyberpunk
                tag3: Competitive
                browser_playable: false
                visibility: true 
              # - game_thumbnail: /gamelib/ordos.png
              #   game_title: Ordos - Order & Chaos
              #   game_release: 12th May, 2020            
              #   game_blog: /blog/ordos/
              #   tag1: Action
              #   tag2: Combat Flight Simulator
              #   tag3: Fantasy
              #   browser_playable: false
              #   visibility: false 
              # - game_thumbnail: /gamelib/westernrunner.png
              #   game_title: Western Runner
              #   game_release: November, 2019            
              #   game_blog: /blog/western-runner/
              #   tag1: Endless Runner
              #   tag2: Casual
              #   tag3: Western
              #   browser_playable: false
              #   visibility: false 
              # - game_thumbnail: /gamelib/capsays.png
              #   game_title: Captain Says
              #   game_release: 31st August, 2019            
              #   game_blog: /blog/captain-says/
              #   tag1: Educational
              #   tag2: Casual
              #   tag3: Arcade
              #   browser_playable: false
              #   visibility: false 
              - game_thumbnail: /gamelib/onlyonerecruit.png
                game_title: Only One Recruit
                game_release: 4th August, 2019           
                game_blog: /blog/only-one-recruit/
                tag1: Teamwork
                tag2: Puzzles
                tag3: Retro
                browser_playable: true
                visibility: true
              - game_thumbnail: /gamelib/boxysee.png
                game_title: Boxy See, Boxy Do
                game_release: 12th July, 2020           
                game_blog: /blog/boxy-see-boxy-do/
                tag1: Teamwork
                tag2: Puzzles
                tag3: Action
                browser_playable: true
                visibility: true
              # - game_thumbnail: /gamelib/aquaadventure.png
              #   game_title: Aqua Adventure
              #   game_release: 3rd December, 2020           
              #   game_blog: /blog/aqua-adventure/
              #   tag1: Shoot em up
              #   tag2: Retro
              #   tag3: Action
              #   browser_playable: false
              #   visibility: false
              - game_thumbnail: /gamelib/somewhereinberkshire.png
                game_title: Somewhere In Berkshire
                game_release: 19th June, 2020           
                game_blog: /blog/somewhere-in-berkshire/
                tag1: Adventure
                tag2: Casual
                tag3: Walking Simulator
                browser_playable: true
                visibility: true
              - game_thumbnail: /gamelib/drivenroundtheloop.png
                game_title: Driven Round The Loop
                game_release: 5th October, 2020          
                game_blog: /blog/driven-round-the-loop/
                tag1: Puzzles
                tag2: Casual
                tag3: Cars
                browser_playable: true
                visibility: true
              - game_thumbnail: /gamelib/thedragonsitter.png
                game_title: The Dragonsitter
                game_release: 21st April, 2020        
                game_blog: /blog/the-dragonsitter/
                tag1: Digital Pet
                tag2: Casual
                tag3: Fantasy
                browser_playable: true
                visibility: true
              - game_thumbnail: /gamelib/villagesim.png
                game_title: Village Simulator
                game_release: 7th October, 2019        
                game_blog: /blog/village-simulator/
                tag1: Simulator
                tag2: Casual
                tag3: City Builder
                browser_playable: true
                visibility: true
              - game_thumbnail: /gamelib/yelapa.png
                game_title: Welcome To Yelapa
                game_release: 21st June, 2019        
                game_blog: /blog/welcome-to-yelapa/
                tag1: Puzzles
                tag2: Adventure
                tag3: Casual
                browser_playable: true
                visibility: true

# social links
twitter_username: datpc_
github_username:  datpc166
facebook_username: quocdat1606
linkedin_username: dylan1606
# behance_username: johndoe
instagram_username: datpc_
medium_username: nqdat160602
telegram_username: Quocdat1606
# dribbble_username: johndoe
# flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 6280

# wakatime username (coding activity)
wakatime_username: dylan

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://nguyenquocdat.us14.list-manage.com/subscribe/post?u=3d5ff9686ce9b892f6ac750b7&amp;id=eff0934e8e

# contact form - (choose formspress or getform)
getform_endpoint: f8ed7d4d-0fb7-46f3-8457-2e5a1d68f124
# formspree_email: nqdat160602@gmail.com

# releases - widget can be (sidebar, modal or embed)
olvy_organization: nguyenquocdat
olvy_widget_type: sidebar
# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# pagination of posts
paginate: 6
per_page: 2
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

collections:
  products:
    output: true
  authors:
    output: true

defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext
  -
    scope:
      path: ""
      type: authors
    values:
      layout: author
      permalink: /blog/authors/:slug

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
